// src/components/Footer.tsx
import { Link } from "react-router-dom";

const Footer = () => {
  return (
    <div className="mt-8 pt-6 border-t border-border text-sm text-muted-foreground">
      <div className="flex items-center gap-4">
        <span className="space-x-1 flex items-center">
          <span>© 2025 smit4k</span>
          <span>•</span>
          <a
            href="https://github.com/smit4k/smit.codes"
            target="_blank"
            rel="noopener noreferrer"
            className="text-link hover:text-link-hover transition-colors"
          >
            Source
          </a>
        </span>
      </div>
    </div>
  );
};

export default Footer;

// frontend/src/lib/components/Footer.svelte
<div class="footer">
	<span>© Smit Patil 2026</span>
	<div class="links">
		<a href="https://github.com/smit4k/smit.codes">Source</a>
	</div>
</div>

<style>
	.footer {
		display: flex;
		justify-content: space-between;
		align-items: center;
		font-size: 1rem;
		color: #bbb;
		margin-top: 1rem;
	}

	.links {
		display: flex;
		gap: 1rem;
	}
</style>
