// src/components/Footer.tsx
import { Link } from "react-router-dom";

const Footer = () => {
  return (
    <div className="mt-8 pt-6 border-t border-border text-sm text-muted-foreground">
      <div className="flex items-center gap-4">
        <span className="space-x-1 flex items-center">
          <span>© 2025 smit4k</span>
          <span>•</span>
          <a
            href="https://github.com/smit4k/smit.codes"
            target="_blank"
            rel="noopener noreferrer"
            className="text-link hover:text-link-hover transition-colors"
          >
            Source
          </a>
        </span>
      </div>
    </div>
  );
};

export default Footer;

// src/lib/components/Footer.svelte
<div class="footer">
	<span>© Smit Patil 2025</span>
	<a href="https://github.com/smit4k/smit.codes">Source</a>
</div>

<style>
	.footer {
		display: flex;
		justify-content: space-between; /* pushes items to edges */
		align-items: center; /* vertically center if multi-line */
		font-size: 0.9rem;
		color: #bbb;
		margin-bottom: 2rem;
	}

	.footer a {
		color: #58a6ff;
		text-decoration: none;
	}

	.footer a:hover {
		text-decoration: underline;
	}
</style>
